apiVersion: v1
kind: Service
metadata:
  name: pgblog
  namespace: pgblog
spec:
  selector:
    app: pgblog
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: pgblog
  namespace: pgblog
spec:
  selector:
    matchLabels:
      app: pgblog
  template:
    metadata:
      labels:
        app: pgblog
    spec:
      containers:
        - name: pgblog
          image: pgblogdev
          imagePullPolicy: Never
          env:
            - name: RAILS_ENV
              value: development
            - name: RAILS_LOG_TO_STDOUT
              value: enabled
            - name: DATABASE_URL
              value: postgresql://pgblog:banana@postgres.pgblog.svc.cluster.local:5432/pgblog
            - name: SELENIUM_REMOTE
              value: http://selenium-chrome.pgblog.svc.cluster.local:4444/wd/hub
            - name: SELENIUM_BROWSER
              value: chrome
            - name: APP_HOST_PORT
              value: "3000"
          volumeMounts:
            - mountPath: /app
              name: app-source
      volumes:
        - name: app-source
          hostPath:
            path: /Users/brianbayer/Lex/learning/syststrails/pgblog
            type: Directory
